// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package Chat

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChittyChatServiceClient is the client API for ChittyChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChittyChatServiceClient interface {
	JoinChat(ctx context.Context, opts ...grpc.CallOption) (ChittyChatService_JoinChatClient, error)
	Publish(ctx context.Context, opts ...grpc.CallOption) (ChittyChatService_PublishClient, error)
}

type chittyChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChittyChatServiceClient(cc grpc.ClientConnInterface) ChittyChatServiceClient {
	return &chittyChatServiceClient{cc}
}

func (c *chittyChatServiceClient) JoinChat(ctx context.Context, opts ...grpc.CallOption) (ChittyChatService_JoinChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChittyChatService_ServiceDesc.Streams[0], "/Chat.ChittyChatService/JoinChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chittyChatServiceJoinChatClient{stream}
	return x, nil
}

type ChittyChatService_JoinChatClient interface {
	Send(*FromClient) error
	CloseAndRecv() (*User, error)
	grpc.ClientStream
}

type chittyChatServiceJoinChatClient struct {
	grpc.ClientStream
}

func (x *chittyChatServiceJoinChatClient) Send(m *FromClient) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chittyChatServiceJoinChatClient) CloseAndRecv() (*User, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(User)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *chittyChatServiceClient) Publish(ctx context.Context, opts ...grpc.CallOption) (ChittyChatService_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChittyChatService_ServiceDesc.Streams[1], "/Chat.ChittyChatService/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &chittyChatServicePublishClient{stream}
	return x, nil
}

type ChittyChatService_PublishClient interface {
	Send(*FromClient) error
	Recv() (*FromServer, error)
	grpc.ClientStream
}

type chittyChatServicePublishClient struct {
	grpc.ClientStream
}

func (x *chittyChatServicePublishClient) Send(m *FromClient) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chittyChatServicePublishClient) Recv() (*FromServer, error) {
	m := new(FromServer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChatServiceServer is the server API for ChittyChatService service.
// All implementations must embed UnimplementedChittyChatServiceServer
// for forward compatibility
type ChittyChatServiceServer interface {
	JoinChat(ChittyChatService_JoinChatServer) error
	Publish(ChittyChatService_PublishServer) error
	mustEmbedUnimplementedChittyChatServiceServer()
}

// UnimplementedChittyChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChittyChatServiceServer struct {
}

func (UnimplementedChittyChatServiceServer) JoinChat(ChittyChatService_JoinChatServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinChat not implemented")
}
func (UnimplementedChittyChatServiceServer) Publish(ChittyChatService_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedChittyChatServiceServer) mustEmbedUnimplementedChittyChatServiceServer() {}

// UnsafeChittyChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChittyChatServiceServer will
// result in compilation errors.
type UnsafeChittyChatServiceServer interface {
	mustEmbedUnimplementedChittyChatServiceServer()
}

func RegisterChittyChatServiceServer(s grpc.ServiceRegistrar, srv ChittyChatServiceServer) {
	s.RegisterService(&ChittyChatService_ServiceDesc, srv)
}

func _ChittyChatService_JoinChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChittyChatServiceServer).JoinChat(&chittyChatServiceJoinChatServer{stream})
}

type ChittyChatService_JoinChatServer interface {
	SendAndClose(*User) error
	Recv() (*FromClient, error)
	grpc.ServerStream
}

type chittyChatServiceJoinChatServer struct {
	grpc.ServerStream
}

func (x *chittyChatServiceJoinChatServer) SendAndClose(m *User) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chittyChatServiceJoinChatServer) Recv() (*FromClient, error) {
	m := new(FromClient)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ChittyChatService_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChittyChatServiceServer).Publish(&chittyChatServicePublishServer{stream})
}

type ChittyChatService_PublishServer interface {
	Send(*FromServer) error
	Recv() (*FromClient, error)
	grpc.ServerStream
}

type chittyChatServicePublishServer struct {
	grpc.ServerStream
}

func (x *chittyChatServicePublishServer) Send(m *FromServer) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chittyChatServicePublishServer) Recv() (*FromClient, error) {
	m := new(FromClient)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChatService_ServiceDesc is the grpc.ServiceDesc for ChittyChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChittyChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Chat.ChittyChatService",
	HandlerType: (*ChittyChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "JoinChat",
			Handler:       _ChittyChatService_JoinChat_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "Publish",
			Handler:       _ChittyChatService_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "Chat/ChittyChatService.proto",
}
