// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package ChittyChatService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChittyChatServiceClient is the client API for ChittyChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChittyChatServiceClient interface {
	ChittyChatService(ctx context.Context, opts ...grpc.CallOption) (ChittyChatService_ChittyChatServiceClient, error)
}

type chittyChatServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChittyChatServiceClient(cc grpc.ClientConnInterface) ChittyChatServiceClient {
	return &chittyChatServiceClient{cc}
}

func (c *chittyChatServiceClient) ChittyChatService(ctx context.Context, opts ...grpc.CallOption) (ChittyChatService_ChittyChatServiceClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChittyChatService_ServiceDesc.Streams[0], "/ChittyChatService.ChittyChatService/ChittyChatService", opts...)
	if err != nil {
		return nil, err
	}
	x := &chittyChatServiceChittyChatServiceClient{stream}
	return x, nil
}

type ChittyChatService_ChittyChatServiceClient interface {
	Send(*FromClient) error
	Recv() (*FromServer, error)
	grpc.ClientStream
}

type chittyChatServiceChittyChatServiceClient struct {
	grpc.ClientStream
}

func (x *chittyChatServiceChittyChatServiceClient) Send(m *FromClient) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chittyChatServiceChittyChatServiceClient) Recv() (*FromServer, error) {
	m := new(FromServer)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChatServiceServer is the server API for ChittyChatService service.
// All implementations must embed UnimplementedChittyChatServiceServer
// for forward compatibility
type ChittyChatServiceServer interface {
	ChittyChatService(ChittyChatService_ChittyChatServiceServer) error
	mustEmbedUnimplementedChittyChatServiceServer()
}

// UnimplementedChittyChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChittyChatServiceServer struct {
}

func (UnimplementedChittyChatServiceServer) ChittyChatService(ChittyChatService_ChittyChatServiceServer) error {
	return status.Errorf(codes.Unimplemented, "method ChittyChatService not implemented")
}
func (UnimplementedChittyChatServiceServer) mustEmbedUnimplementedChittyChatServiceServer() {}

// UnsafeChittyChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChittyChatServiceServer will
// result in compilation errors.
type UnsafeChittyChatServiceServer interface {
	mustEmbedUnimplementedChittyChatServiceServer()
}

func RegisterChittyChatServiceServer(s grpc.ServiceRegistrar, srv ChittyChatServiceServer) {
	s.RegisterService(&ChittyChatService_ServiceDesc, srv)
}

func _ChittyChatService_ChittyChatService_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChittyChatServiceServer).ChittyChatService(&chittyChatServiceChittyChatServiceServer{stream})
}

type ChittyChatService_ChittyChatServiceServer interface {
	Send(*FromServer) error
	Recv() (*FromClient, error)
	grpc.ServerStream
}

type chittyChatServiceChittyChatServiceServer struct {
	grpc.ServerStream
}

func (x *chittyChatServiceChittyChatServiceServer) Send(m *FromServer) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chittyChatServiceChittyChatServiceServer) Recv() (*FromClient, error) {
	m := new(FromClient)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChittyChatService_ServiceDesc is the grpc.ServiceDesc for ChittyChatService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChittyChatService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ChittyChatService.ChittyChatService",
	HandlerType: (*ChittyChatServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChittyChatService",
			Handler:       _ChittyChatService_ChittyChatService_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "ChittyChatService/ChittyChatService.proto",
}
